services:
  # This is only required if you're running it stand-alone; on the deployment it shares a VM,
  # so the nginx file has to be used by the actual VM-level Nginx.
  nginx:
    container_name: physics-workload-nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: "${PROJECT_PATH}/nginx/physics_workload.conf"
        target: "/etc/nginx/conf.d/default.conf"
      - type: bind
        source: "${PROJECT_PATH}/logs/"
        target: "/var/www/physics-workload/logs/"
      - type: bind
        source: "${PROJECT_PATH}/staticfiles/"
        target: "/var/www/physics-workload/staticfiles/"
      - type: bind
        source: "/etc/tls/certs/"
        target: "/etc/tls/certs/"
      - type: bind
        source: "/etc/tls/private/"
        target: "/etc/tls/private/"

    restart: unless-stopped
    depends_on:
      - web

  web:
    container_name: physics-workload-django
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8008:8000"
    env_file:
      - "./.env.default"
      - "./.env"
    volumes:
      - type: bind
        source: "${PROJECT_PATH}/data/"
        target: "/var/www/physics-workload/data/"
      - type: bind
        source: "${PROJECT_PATH}/staticfiles/"
        target: "/var/www/physics-workload/staticfiles/"
      - type: bind
        source: "${PROJECT_PATH}/logs/"
        target: "/var/www/physics-workload/logs/"
    command:
      - "bash"
      - "docker-entrypoint.sh"
    restart: unless-stopped
