services:
  physics_workload_nginx:
    container_name: physics-workload-nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: "./nginx/app.conf"
        target: "/etc/nginx/conf.d/default.conf"
      - type: bind
        source: "/etc/pki/tls/certs/"
        target: "/etc/pki/tls/certs/"
      - type: bind
        source: "/etc/pki/tls/private/"
        target: "/etc/pki/tls/private/"
      - type: bind
        source: "${PROJECT_PATH}/logs/"
        target: "/var/www/physics-workload/logs/"
      - type: bind
        source: "${PROJECT_PATH}/app/static/"
        target: "/var/www/physics-workload/app/static/"
    restart: unless-stopped
    depends_on:
      - django

  physics_workload_django:
    container_name: physics-workload-django
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    env_file:
      - "./.env.default"
      - "./.env"
    volumes:
      - type: bind
        source: "${PROJECT_PATH}/db.sqlite3"
        target: "/var/www/physics-workload/db.sqlite3"
    restart: unless-stopped
