services:
  nginx:
    container_name: physics-workload-nginx
    image: nginx:latest
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - type: bind
        source: "${PROJECT_PATH}/nginx/app.conf"
        target: "/etc/nginx/conf.d/default.conf"
      - type: bind
        source: "${PROJECT_PATH}/logs/"
        target: "/var/www/physics-workload/logs/"
      - type: bind
        source: "${PROJECT_PATH}/staticfiles/"
        target: "/var/www/physics-workload/staticfiles/"
      - type: bind
        source: "/etc/tls/certs/"
        target: "/etc/tls/certs/"
      - type: bind
        source: "/etc/tls/private/"
        target: "/etc/tls/private/"

    restart: unless-stopped
    depends_on:
      - web

  web:
    container_name: physics-workload-django
    build:
      dockerfile: Dockerfile
      context: .
    expose:
      - "8000"
    env_file:
      - "./.env.default"
      - "./.env"
    volumes:
      - type: bind
        source: "${PROJECT_PATH}/data/"
        target: "/var/www/physics-workload/data/"
      - type: bind
        source: "${PROJECT_PATH}/staticfiles/"
        target: "/var/www/physics-workload/staticfiles/"
      - type: bind
        source: "${PROJECT_PATH}/logs/"
        target: "/var/www/physics-workload/logs/"
    command:
      - "bash"
      - "docker-entrypoint.sh"
    restart: unless-stopped
