services:
  physics_workload_nginx:
    container_name: physics-workload-nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: "./nginx/app.conf"
        target: "/etc/nginx/conf.d/default.conf"
      - type: bind
        source: "/etc/tls/certs/"
        target: "/etc/tls/certs/"
      - type: bind
        source: "/etc/tls/private/"
        target: "/etc/tls/private/"
      - type: bind
        source: "${PROJECT_PATH}/logs/"
        target: "/var/www/physics-workload/logs/"
      - type: bind
        source: "${PROJECT_PATH}/static/"
        target: "/var/www/physics-workload/static/"
    restart: unless-stopped
    depends_on:
      - physics_workload_django

  physics_workload_django:
    container_name: physics-workload-django
    build:
      dockerfile: Dockerfile
      context: .
    expose:
      - "8000"
    env_file:
      - "./.env.default"
      - "./.env"
    volumes:
      - type: bind
        source: "${PROJECT_PATH}/data/"
        target: "/var/www/physics-workload/data/"
      - type: bind
        source: "${PROJECT_PATH}/static/"
        target: "/var/www/physics-workload/static/"
      - type: bind
        source: "${PROJECT_PATH}/logs/"
        target: "/var/www/physics-workload/logs/"
    command:
      - "uv"
      - "run"
      - "manage.py"
      - "runserver"
      - "0.0.0.0:8000"
    restart: unless-stopped
